- type: loadout
  id: SecurityFirearmWeaponEnergyShotgun
  equipment:
   suitstorage: WeaponEnergyShotgun

- type: loadout
  id: SecurityWeaponEnergySwordHoS
  equipment:
   back: EnergySwordHoS

- type: loadout
  id: SecurityFirearmWeaponEnergyGunMultiphase
  equipment:
   suitstorage: WeaponEnergyGunMultiphase

- type: loadout
  id: SecurityFirearmWeaponSubMachineGunC20rHoS
  equipment:
   suitstorage: WeaponSubMachineGunC20rHoS

- type: loadout
  id: SecurityFirearmWeaponPulsePistol
  equipment:
   back: WeaponPulsePistol
