- type: entity
  name: pepperspray
  id: PepperSpray
  parent: [BaseItem, BaseSecurityContraband]
  suffix: Filled
  description: A small 50u canister of Oleoresin Capsaicin. Capable of blinding and stunning targets who aren't wearing protective gear.
  components:
    - type: Tag
      tags:
        - PepperSpray
    - type: Sprite
      sprite: /Textures/_Goobstation/Objects/Specific/Security/pepperspray.rsi
      layers:
        - state: icon
    - type: Item
      size: Small
      sprite: /Textures/_Goobstation/Objects/Specific/Security/pepperspray.rsi
    - type: RefillableSolution
      solution: spray
    - type: SolutionContainerManager
      solutions:
        spray:
          maxVol: 50
          reagents:
            - ReagentId: OleoresinCapsaicin
              Quantity: 50
    - type: Spray
      transferAmount: 10
      sprayVelocity: 3
      sprayDistance: 2.5
      spraySound:
        path: /Audio/Effects/spray2.ogg
    - type: UseDelay
    - type: StaticPrice
      price: 25
